### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gbanister**
using IsInstanceOfType will allow a resource to be protected by an attribute that derives from AuthorizeAttribute

### CODE REVIEW

**Comment by heldersepu** [comment]
Can you create a unit test showing the problem?

**Comment by gbanister** [comment]
The failing test is added here: 
https://github.com/gbanister/Swagger-Net <https://github.com/gbanister/Swagger-Net>

Would you like me to submit a PR with the failing test?

**Comment by gbanister** [comment]
The failing test is here:
https://github.com/gbanister/Swagger-Net/blob/71b5900e505558e71a679d9fccf1c59f6e965a8f/Tests/Swagger.Net.Tests/Swagger/SchemaTests.cs#L1113-L1139 <https://github.com/gbanister/Swagger-Net/blob/71b5900e505558e71a679d9fccf1c59f6e965a8f/Tests/Swagger.Net.Tests/Swagger/SchemaTests.cs#L1113-L1139>

**Comment by gbanister** [comment]
No, I noticed the problem when the resources that were protected by a custom attribute deriving from the AuthorizeAttribute were not getting the LOCK icon in the Swagger UI.

**Comment by heldersepu** [comment]
I meant the current build failures on appveyor: 
https://ci.appveyor.com/project/heldersepu/swashbuckle/builds/19350056

**Comment by heldersepu** [comment]
```
Errors, Failures and Warnings
1) Failed : Swagger.Net.Tests.Swagger.SchemaTestsWithCustomAuthorizeAttribute.It_adds_security_to_protected_operations
  Expected: not null
  But was:  null
   at Swagger.Net.Tests.Swagger.SchemaTestsWithCustomAuthorizeAttribute.It_adds_security_to_protected_operations() in
 C:\projects\swashbuckle\Tests\Swagger.Net.Tests\Swagger\SchemaTests.cs:line 1137
```

**Comment by heldersepu** [comment]
I think I understand now... looking at your commit history you meant to show the error

**Comment by gbanister** [comment]
Yes, sorry for misunderstanding.

**Pull request merged**
