### PR TITLE
Update VersionInfoBuilder

### PR DESCRIPTION
**Pull request by vivek201**
Allow versions to be saved as is

### CODE REVIEW

**Comment by heldersepu** [comment]
Fix the unit tests and add proper ones

**Comment by vivek201** [comment]
The unit tests passes once I fixed the Generate method in SwaggerDocHandler

**Comment by heldersepu** [comment]
I think this was done to make the Version case insensitive...
What are you trying to fix?

**Comment by vivek201** [comment]
Well, the issue is that I have an api project with routes registered with lowercase versions. And those don't get displayed with the uppercase version.

**Comment by heldersepu** [comment]
Can you share your config?

**Comment by heldersepu** [comment]
Sorry I'm closing this, I added more details to the issue to the

**Comment by vivek201** [comment]
@heldersepu I found the issue in my version resolver. Sorry for the trouble

**Pull request closed without merging**
