### PR TITLE
example for parameters

### PR DESCRIPTION
**Pull request by TheBlackReverand**

### CODE REVIEW

**Comment by heldersepu** [comment]
Can you add some unit tests?

**Comment by TheBlackReverand** [comment]
Sorry, I do it on my work time and I just saw your message. Next time I make the unit tests.

Thanks for pulling

**Comment by heldersepu** [comment]
@TheBlackReverand 
Take a look at:
https://online.swagger.io/validator/debug?url=http://swashbuckletest.azurewebsites.net/swagger/docs/V1
It seems that the example is not valid there, Did you research this on the specs?

**Comment by TheBlackReverand** [comment]
@heldersepu 
I found "example" in parameter here and that work fine on my project :\
https://swagger.io/docs/specification/describing-parameters/#parameter-examples-14

**Comment by heldersepu** [comment]
OAS 3
that is a problem we still on 2

**Comment by heldersepu** [comment]
To keep the schema compatible with OAS 2.0 I had to change it to `x-example` see commit: https://github.com/heldersepu/Swagger-Net/commit/85912d406c2b06b1f19148abf19444fc29bedf2e
I hope that works for you...

**Comment by TheBlackReverand** [comment]
Flag `x-example` is generated but swagger-ui (integrated with Swagger-Net) don't use it :\
You can see differences in screencapture.

I understand that Swashbuckle is dedicated to the V2 standard and Swagger-Net to the V3 standard, I'm wrong?

example
example-tryit
x-example
x-example-tryit

**Comment by heldersepu** [comment]
I see your point! That is the root of much confusion Swagger-UI vs OAS the version numbers are similar
Swagger-Net uses [OAS 2](https://github.com/heldersepu/Swagger-Net/blob/master/Swagger.Net/Swagger/SwaggerDocument.cs#L8) and [Swagger-UI 3.9.2](https://github.com/swagger-api/swagger-ui/releases/tag/v3.9.2)

OAS 3 still not supported by many tools out there, you can see that Swagger-UI started support just recently:
https://github.com/swagger-api/swagger-ui#compatibility

For your case maybe you should set a default to that param

**Comment by heldersepu** [comment]
Here is an example using a default value:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/Attribute/Attribute_Get
and here is the code behind that:
https://github.com/heldersepu/SwashbuckleTest/blob/1158ec65ae462cee1dd5b4e17af0f70f59052bd9/Swagger_Test/Controllers/AttributeController.cs#L10

**Comment by TheBlackReverand** [comment]
Yes, before I use `default` but with that in last swagger-ui `example` and `default` value or mixed.

Before swagger-ui don't show it (just use it for TryIt form input)
diff-swagger-ui

**Comment by heldersepu** [comment]
Let me push a new version so you get latest (Swagger-Net 8.3.9.202)

**Comment by heldersepu** [comment]
https://www.nuget.org/packages/Swagger-Net/8.3.9.202

**Comment by TheBlackReverand** [comment]
With Swagger-Net 8.3.9.202 and use the `parameter.@default` I have the same result of 8.3.9.103.

example go in tryit form ==> OK
example go in "Default value" description instead of real default value ==> Not ok because ambigous

Maybe we can't have coexistence between "Default value" and "Example" with OAS 2. It's not a problem, I can work with a fork of  Swagger-Net as long as you use OAS 3.

**Comment by TheBlackReverand** [comment]
- With Swagger-Net 8.3.9.202 and use the parameter.@default I have the same result of 8.3.9.103.
  - example go in tryit form ==> OK
  - example go in "Default value" description instead of real default value ==> Not ok because ambigous
- With Swagger-Net 8.3.9.202 and use the parameter.example (write x-example in json) my example is not visible.

Maybe we can't have coexistence between "Default value" and "Example" with OAS 2. It's not a problem, I can work with a fork of Swagger-Net as long as you use OAS 3.

**Comment by heldersepu** [comment]
Sorry I'm not quite sure what you mean...
what is this "real default value" that you mention?

**Comment by TheBlackReverand** [comment]
real default value ==> value used if (in production situation, not swagger call) not value transmitted

**Comment by heldersepu** [comment]
The default value is a value used if no param is supplied...
That is the value that Swagger-UI uses on the [Try it out] to prepopulate the inputs

sorry but there is not an option for "if in production situation" if you need something like that you might need to code an IDocumentFilter

**Comment by heldersepu** [comment]
If you need additional documentation consider using the `summary` and `remarks` xml tags:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/ApiExplorer/ApiExplorer_Get
code behind here:
https://github.com/heldersepu/SwashbuckleTest/blob/master/Swagger_Test/Controllers/ApiExplorerController.cs#L10

**Comment by TheBlackReverand** [comment]
> The default value is a value used if no param is supplied...
> That is the value that Swagger-UI uses on the [Try it out] to prepopulate the inputs

I'm agree with you, but some default value are null and I want give an example for Swagger consummers.
Because a string value can take several forms.
If I use parameter.@default I'm afraid Swagger users will misunderstand the documentation.

> If you need additional documentation consider using the summary and remarks xml tags

Yes I use it for a textual explanation but this is not worth a good example case ;)

**Comment by heldersepu** [comment]
I wish I could help more on this issue you are having, but I do not see a quick way forward
- Adding example while we use `OAS 2` will make the swagger.json doc fail validation
- To jump to `OAS 3` we will need to do a lot more research to see what breaks

**Comment by TheBlackReverand** [comment]
Yes I'm agree with you.

It's not a problem, you can revert my pull request if you need it, I think I'm gonna run a fork.

**Comment by heldersepu** [comment]
I opened a request with team that handles OAS, if you can leave a comment there showing your interest for that feature:
https://github.com/OAI/OpenAPI-Specification/issues/1477
I don't think they will approve it, will see.

**Comment by heldersepu** [comment]
@TheBlackReverand  I was looking at a relatively new option: `showExtensions`

That might be what you need and it will keep you OAS compliant.
Here is how it looks like:
http://swashbuckletest.azurewebsites.net/swagger/ui/index#/IHttpActionResult/IHttpActionResult_GetById

**Comment by TheBlackReverand** [comment]
Yes It's good option, with this we can see our test case but for now I can't come back on official NuGet package (too many changes already push in production) but I let my fork up-to-date with regular ReBase.

If you like something on it (global header, add example on schema but different example per URL...) you can integrate it ;)

Thanks for your investigation

**Comment by heldersepu** [comment]
@TheBlackReverand  sorry but I do not see your fork anymore...

**Comment by TheBlackReverand** [comment]
@heldersepu It's because I have delete it, this is my personnal account, I have a new fork with company account => https://github.com/ecoburotic/Swagger-Net

**Pull request merged**
